### ISSUE TITLE
Crash with LimeLib

### ISSUE THREAD

**Issue by jsaggers** [Lemonszz/Anima-Mundi#8]
I am getting a crash between Anima Mundi and LimeLib, seems to be when LimeLib tries to display power information about the blocks.

Will post it here and on the LimeLib github since both are mentioned in the report.

Crash
---- Minecraft Crash Report ----
Description: Ticking player
java.lang.ClassCastException: party.lemons.anima.energy.AnimaStorage cannot be cast to net.minecraftforge.energy.IEnergyStorage
	at mrriegel.limelib.helper.EnergyHelper.getEnergy(EnergyHelper.java:61)
	at mrriegel.limelib.network.EnergySyncMessage.<init>(EnergySyncMessage.java:31)
	at mrriegel.limelib.util.EventHandler.playerTick(EventHandler.java:117)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_EventHandler_playerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:372)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:376)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:286)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:171)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)
---------------------------------------------------------------------------------------
-- Head --
Thread: Server thread
Stacktrace:
	at mrriegel.limelib.helper.EnergyHelper.getEnergy(EnergyHelper.java:61)
	at mrriegel.limelib.network.EnergySyncMessage.<init>(EnergySyncMessage.java:31)
	at mrriegel.limelib.util.EventHandler.playerTick(EventHandler.java:117)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_EventHandler_playerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:372)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:376)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:286)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 155
	Entity Name: jasonsaggers
	Entity's Exact location: -53.61, 88.00, 807.54
	Entity's Block location: World: (-54,88,807), Chunk: (at 10,5,7 in -4,50; contains blocks -64,0,800 to -49,255,815), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:171)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@2925aa49
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)

**Comment by Lemonszz** [comment]
Make sure you have the latest version, I believe that should be fixed.

**Comment by jsaggers** [comment]
I am using 0.1.1 for 1.12, I don't have any problems until I install LimeLib, Which I have installed for because another mod requires it.

**Comment by Lemonszz** [comment]
Just tested it myself and got the same crash, thanks for the report.

**Comment by Lemonszz** [comment]
I've just uploaded a fixed version to curseforge, it might take a few minutes to get approved.

Thanks for helping out!
